<div class="form-signin w-100 m-auto">
    <form action="/login" method="post">
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
        <?= $this->flash->output(); ?>
        <div class="form-floating">
            <?= $form->render('username') ?>
            <label for="username">Username</label>
        </div>
        <div class="form-floating">
            <?= $form->render('password') ?>
            <label for="password">Password</label>
        </div>

        <div class="form-check text-start my-3">
            <?= $form->render('remember') ?>
            <label class="form-check-label" for="remember">
                Remember me
            </label>
        </div>
        <button class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
    </form>
</div>