<div class="row">
    <div class="col">
        <h1 class="mt-5">Holidays Request</h1>
    </div>
    <div class="col d-flex flex-row-reverse">
        <Button type="button" class="btn btn-success mt-5" onclick="location.href='<?=$this->url->get('private/manipulation')?>'">New</Button>
    </div>
</div>
<div class="row">
    <div class="col">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col" width="10%">#</th>
                    <th scope="col" class="th-lg" width="15%">Name</th>
                    <th scope="col" class="th-lg" width="10%">Date</th>
                    <th scope="col" class="th-lg" width="25%">Reason</th>
                    <th scope="col" class="th-lg" width="10%">Apply</th>
                    <th scope="col" class="th-lg" width="30%" style="text-align:center">Options</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                <?php
                foreach ($events->items as $event) {
                    echo '<tr>
                    <th scope="row">' . $event->id . '</th>
                    <td>' . $event->user->name . '</td>
                    <td>' . $event->date . '</td>
                    <td>' . $event->reason . '</td>
                    <td>' . $event->apply . '</td>
                    <td style="text-align:center">
                        <button type="button" class="btn btn-danger" onClick="location.href=\''.$this->url->get('private/delete/' . $event->id).'\'">Delete</button>
                        <button type="button" class="btn btn-primary" onClick="location.href=\''.$this->url->get('private/manipulation/' . $event->id).'\'">Edit</button>';
                    if ($showBtn) {
                        echo ' <button type="button" class="btn btn-success" onClick="location.href=\''.$this->url->get('private/apply/' . $event->id).'\'">Apply</button>';
                    }
                    echo '</td></tr>';
                }
                ?>
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col d-flex flex-row-reverse">
        <nav>
            <ul class="pagination">
                <?php
                $total_pages = ceil($events->total_items / $events->limit);
                ?>
                <!-- Enlace a la página anterior -->
                <?php if ($events->current > 1) : ?>
                    <li class="page-item"><a class="page-link" href="?page=<?php echo $events->previous; ?>">Previous</a></li>
                <?php endif; ?>

                <!-- Enlaces a cada página (limitados) -->
                <?php
                $start = max($events->current - 5, 1);
                $end = min($events->current + 5, $total_pages);
                for ($i = $start; $i <= $end; $i++) : ?>
                    <li class="page-item"><a class="page-link" href="?page=<?php echo $i; ?>" <?php if ($i == $events->current) : ?>style="font-weight:bold;" <?php endif; ?>><?php echo $i; ?></a></li>
                <?php endfor; ?>

                <!-- Enlace a la página siguiente -->
                <?php if ($events->current < $total_pages) : ?>
                    <li class="page-item"><a class="page-link" href="?page=<?php echo $events->next; ?>">Next</a></li>
                <?php endif; ?>
            </ul>
        </nav>
    </div>
</div>