<?= Phalcon\Tag::getDocType() ?>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Holidays Application</title>
  <?= Phalcon\Tag::stylesheetLink(
    [
      'href' => 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css',
      'crossorigin' => 'anonymous',
      'referrerpolicy' => 'no-referrer'
    ],
    false
  ) ?>
  <?= Phalcon\Tag::stylesheetLink('css/styles.css') ?>
</head>

<body>
  <div class="container"><?= $this->getContent() ?></div>
  <?= Phalcon\Tag::javascriptInclude(
    [
      'src'  => 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.bundle.min.js',
      'type' => 'application/javascript',
      'crossorigin' => 'anonymous',
      'referrerpolicy' => 'no-referrer'
    ],
    false
  ) ?>
</body>

</html>