<?= Phalcon\Tag::getDocType() ?>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Holidays Admin Application</title>
    <?= Phalcon\Tag::stylesheetLink(
        [
            'href' => 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css',
            'crossorigin' => 'anonymous',
            'referrerpolicy' => 'no-referrer'
        ],
        false
    ) ?>
</head>

<body>
    <header class="navbar sticky-top bg-dark p-0 shadow" data-bs-theme="dark">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">PRIVATE ZONE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="<?= $this->url->get('private') ?>"> Home</a>
                        </li>
                    </ul>

                    <div class="collapse navbar-collapse justify-content-end">
                        <a type="button" class="btn btn-danger" href="<?= $this->url->get('private/logout') ?>">Logout</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main class="flex-shrink-0">
        <div class="container"><?= $this->getContent() ?></div>
    </main>
    <?= Phalcon\Tag::javascriptInclude(
        [
            'src'  => 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.bundle.min.js',
            'type' => 'application/javascript',
            'crossorigin' => 'anonymous',
            'referrerpolicy' => 'no-referrer'
        ],
        false
    ) ?>
</body>

</html>